remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-sitemap
gem "github-pages", group: :jekyll_plugins
title: "Catventures: A Dark & Broken World"
desciption: "- "